language: generic
sudo: required
dist: trusty

script:
  - bash get_info.sh
  - bash check_url.sh
  - bash publish.sh

# deploy
deploy:
  - provider: pages
    target-branch: history
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    local-dir: history
    on:
      branch: master

