language: python
sudo: required
dist: trusty

script:
  - sudo bash get_info.sh
  - sudo bash check_url.sh
  - sudo bash publish.sh

# deploy
#deploy:
#  - provider: pages    # Deploy master to branch win-build
#    skip-cleanup: true
#    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
#    keep-history: false
#    local-dir: docs
#    on:
#      branch: master

