language: generic
sudo: required
dist: trusty

script:
  - bash fb-api-test.sh

# deploy
#deploy:
#  - provider: pages    # Deploy master to branch win-build
#    skip-cleanup: true
#    github-token: $GH_TOKEN  # Set in travis-ci.org dashboard
#    keep-history: false
#    local-dir: docs
#    on:
#      branch: master

